// <auto-generated />
using System;
using LLMProxy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LLMProxy.Data.Migrations
{
    [DbContext(typeof(ProxyDbContext))]
    [Migration("20250509225212_AddEffectiveModelToLog")]
    partial class AddEffectiveModelToLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("LLMProxy.Models.ApiLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientRequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectiveModelName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProxyResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedModel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamBackendName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamRequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpstreamStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpstreamUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasSuccess")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ApiLogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
